server:
  port: 31001
  max-http-header-size: 10000000
spring:
  application:
    name: xc-service-manage-cms
  data:
    mongodb:
      uri:  mongodb://root:123@localhost:27017
      database: xc_cms
      username: root
      password: 123